CREATE TABLE TEST01 (A VARCHAR2(10) PRIMARY KEY, B NUMBER);
DECLARE
  PL_CNT NUMBER;
BEGIN
  PL_CNT :=0;
  LOOP
  PL_CNT := PL_CNT + 1;
  EXIT WHEN PL_CNT > 1000;
  INSERT INTO TEST01 VALUES
  (LPAD(TO_CHAR(PL_CNT),5,'0'),PL_CNT);
  END LOOP;
 COMMIT;
END;
