CREATE  TABLE TEST08 (SITE   VARCHAR2(5) NOT NULL,
                      DEPT   VARCHAR2(5) NOT NULL,
                      LEV    VARCHAR2(2) NOT NULL,
                      LOCAL  VARCHAR2(6) NOT NULL,
                      NO_EMP NUMBER,
                      CONSTRAINT TEST08_PK PRIMARY KEY (SITE,DEPT,LEV,LOCAL)
                     );
INSERT INTO TEST08
SELECT SITE,DEPT,LEV,LOCAL,DECODE(MOD(ROWNUM,2),0,2,1)
FROM  (SELECT 'SITE1' SITE FROM DUAL UNION ALL SELECT 'SITE2' SITE FROM DUAL) A,
 (SELECT 'DEPT1' DEPT FROM DUAL UNION ALL SELECT 'DEPT2' DEPT FROM DUAL UNION ALL
  SELECT 'DEPT3' DEPT FROM DUAL UNION ALL SELECT 'DEPT4' DEPT FROM DUAL) B,
 (SELECT '서울' LOCAL FROM DUAL UNION ALL SELECT '경기' LOCAL FROM DUAL UNION ALL 
  SELECT '경상' LOCAL FROM DUAL UNION ALL SELECT '전라' LOCAL FROM DUAL) C,
 (SELECT 'A'  LEV FROM DUAL UNION ALL SELECT 'B'  LEV FROM DUAL UNION ALL
  SELECT 'C'  LEV FROM DUAL) D;
COMMIT;